version: "3"

services:
  
  transmission:
    container_name: transmission
    build: ./transmission
    image: transmission
    user: 1000:1000
    volumes:
      - ./transmission/config:/config
      - /mnt/media:/media
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    environment:
      TZ: Europe/Paris
    restart: unless-stopped

  sonarr:
    container_name: sonarr
    build: ./sonarr
    image: sonarr
    user: 1000:1000
    volumes:
      - ./sonarr/config:/config
      - /mnt/media:/media
    ports:
      - 8989:8989
    environment:
      TZ: Europe/Paris
    restart: unless-stopped

  radarr:
    container_name: radarr
    build: ./radarr
    image: radarr
    user: 1000:1000
    volumes:
      - ./radarr/config:/config
      - /mnt/media:/media
    ports:
      - 7878:7878
    environment:
      TZ: Europe/Paris
    restart: unless-stopped

networks:
  default:
    ipam:
      config:
        - subnet: 10.0.1.0/24
